import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', loadComponent: () => import('./features/home/home').then((m) => m.Home), data: { title: 'Twinpeaks | Creative & Technology Solutions', description: 'Twinpeaks delivers creative branding, digital solutions, web development, and custom software. Empowering businesses with innovative technology across Africa.', keywords: 'creative agency, web design, branding, digital solutions, software development, graphic design' } },
  { path: 'products', loadComponent: () => import('./features/products/product-list/product-list').then((m) => m.ProductList), data: { title: 'Products & Solutions | Twinpeaks', description: 'Explore our range of creative and technology products: branding kits, design templates, custom software, and digital platform solutions.', keywords: 'design products, software solutions, digital tools, technology products' } },
  { path: 'products/:slug', loadComponent: () => import('./features/products/product-detail/product-detail').then((m) => m.ProductDetail), data: { title: 'Product Details | Twinpeaks', description: 'View details for a Twinpeaks product, including description, pricing, and related information.', keywords: 'product details, Twinpeaks product' } },
  { path: 'services', loadComponent: () => import('./features/services/service-list/service-list').then((m) => m.ServiceList), data: { title: 'Services | Twinpeaks', description: 'Our services include branding & graphic design, website development, custom software, digital marketing, printing, and smart technology solutions.', keywords: 'branding, graphic design, web development, software development, digital marketing, creative services' } },
  { path: 'projects', loadComponent: () => import('./features/projects/project-list/project-list').then((m) => m.ProjectList), data: { title: 'Portfolio & Case Studies | Twinpeaks', description: 'Discover our portfolio of successful projects showcasing creative design, web development, branding, and technology solutions.', keywords: 'portfolio, case studies, project gallery, design work, web projects' } },
  { path: 'projects/:slug', loadComponent: () => import('./features/projects/project-detail/project-detail').then((m) => m.ProjectDetail) },
  { path: 'gallery', redirectTo: 'projects', pathMatch: 'full' },
  { path: 'about', loadComponent: () => import('./features/leadership/leadership-list/leadership-list').then((m) => m.LeadershipList), data: { title: 'About Us | Twinpeaks', description: 'Learn about Twinpeaks, our mission, vision, and experienced team dedicated to creative excellence and innovative technology solutions.', keywords: 'about us, our team, company mission, creative agency, company values' } },
  { path: 'leadership', redirectTo: 'about' },
  { path: 'contact', loadComponent: () => import('./features/contact/contact').then((m) => m.Contact), data: { title: 'Contact Us | Twinpeaks', description: 'Get in touch with our creative team. Contact us for branding, web development, design, or custom software inquiries.', keywords: 'contact us, get in touch, creative agency, design inquiry' } },
  { path: '404', loadComponent: () => import('./features/not-found/not-found').then((m) => m.NotFound), data: { title: '404 Page Not Found | Twinpeaks', description: 'The page you are looking for does not exist. Please return to our site to explore our services.' } },
  { path: '**', redirectTo: '/404' },
];
